version: '3'

services:
  nginx:
    build:
      context: ./src/nginx
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
  
  app:
    build:
      context: ./src/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: "node index.js"
    tty: true
    volumes:
      - ./src/node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./src/mysql:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
